const KEY='money_v2';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{currency:'JOD',salary:{base:0,actual:{}},fixed:[],transactions:[],savingGoal:0};
const $=s=>document.querySelector(s);const fmt=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};const current=()=>monthKey(new Date());const monthTx=()=>db.transactions.filter(t=>monthKey(t.date)===current());
const income=()=>monthTx().filter(t=>t.type==='income').reduce((a,t)=>a+Number(t.amount),0);const expenses=()=>monthTx().filter(t=>t.type==='expense').reduce((a,t)=>a+Number(t.amount),0);
function ensureMonth(){const m=current();let changed=false;const salary=db.salary.actual[m]??db.salary.base;if(salary>0){let t=db.transactions.find(x=>x.auto==='salary'&&x.month===m);if(!t){db.transactions.push({id:'salary-'+m,type:'income',amount:salary,name:'راتب الشهر',category:'راتب',date:new Date(m+'-01T09:00:00').toISOString(),icon:'💵',auto:'salary',month:m});changed=true}else if(Number(t.amount)!==Number(salary)){t.amount=salary;changed=true}}
db.fixed.forEach(f=>{if(Number(f.amount)>0){let t=db.transactions.find(x=>x.auto==='fixed-'+f.id&&x.month===m);if(!t){db.transactions.push({id:'fixed-'+f.id+'-'+m,type:'expense',amount:Number(f.amount),name:f.name,category:f.category||'ثابت',date:new Date(m+'-02T09:00:00').toISOString(),icon:f.category==='الجمعية'?'👥':'🔁',auto:'fixed-'+f.id,month:m});changed=true}}});if(changed)save()}
function render(){ensureMonth();const inc=income(),exp=expenses(),bal=inc-exp, fixed=monthTx().filter(t=>t.type==='expense'&&t.auto&&String(t.auto).startsWith('fixed-')).reduce((a,t)=>a+Number(t.amount),0);$('#available').textContent=fmt(bal);$('#spentHero').textContent=fmt(exp);$('#incomeHero').textContent=fmt(inc);$('#savingHero').textContent=fmt(Math.max(0,bal));$('#incomeStat').textContent=fmt(inc);$('#expenseStat').textContent=fmt(exp);$('#savingStat').textContent=fmt(Math.max(0,bal));$('#fixedStat').textContent=fmt(fixed);$('#currencyLabel').textContent=db.currency;$('#monthLabel').textContent=new Date().toLocaleDateString('ar-JO',{month:'long',year:'numeric'});$('#budgetProgress').style.width=inc?Math.min(100,exp/inc*100)+'%':'0%';$('#salaryMini').textContent=db.salary.base?`${fmt(db.salary.base)} ${db.currency} شهريًا`:'اضغط لضبط الراتب';$('#savingGoalText').textContent=db.savingGoal?`${fmt(Math.max(0,bal))} / ${fmt(db.savingGoal)} ${db.currency}`:'حدد هدفك';const home=monthTx().filter(t=>t.type==='expense'&&t.category==='البيت').reduce((a,t)=>a+Number(t.amount),0);$('#homeMini').textContent=`${fmt(home)} ${db.currency} هذا الشهر`;$('#groupMini').textContent=(db.fixed.filter(f=>f.category==='الجمعية').reduce((a,f)=>a+Number(f.amount),0)?fmt(db.fixed.filter(f=>f.category==='الجمعية').reduce((a,f)=>a+Number(f.amount),0))+' '+db.currency+' شهريًا':'أضف الجمعية');renderRecent();renderReport()}
function renderRecent(){const box=$('#recentList'),arr=[...monthTx()].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,7);if(!arr.length){box.innerHTML='<div class="empty">لسا ما سجلت حركات هذا الشهر.<br>ابدأ براتبك أو أول مصروف 💰</div>';return}box.innerHTML=arr.map(t=>`<div class="tx"><div class="tx-icon">${t.icon||'🧾'}</div><div class="tx-main"><b>${esc(t.name)}</b><small>${esc(t.category||'عام')} • ${new Date(t.date).toLocaleDateString('ar-JO')}</small></div><div class="tx-amount ${t.type==='expense'?'minus':'plus'}">${t.type==='expense'?'−':'+'}${fmt(t.amount)}</div></div>`).join('')}
function renderReport(){const inc=income(),exp=expenses(),pct=inc?Math.min(100,exp/inc*100):0;$('#reportIncome').textContent=fmt(inc);$('#reportExpense').textContent=fmt(exp);$('#reportBalance').textContent=fmt(inc-exp);$('#donutPct').textContent=Math.round(pct)+'%';$('#donut').style.background=`conic-gradient(#6bc89b 0 ${pct*3.6}deg,#263245 ${pct*3.6}deg 360deg)`;const map={};monthTx().filter(t=>t.type==='expense').forEach(t=>map[t.category||'أخرى']=(map[t.category||'أخرى']||0)+Number(t.amount));const arr=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,7),max=arr[0]?.[1]||1;$('#categoryBars').innerHTML=arr.length?arr.map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${fmt(v)}</b></div>`).join(''):'<div class="empty">سجل مصاريف لتظهر لك الرسومات.</div>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}
function salaryForm(){const m=current(),actual=db.salary.actual[m]??db.salary.base;openModal(`<div class="form"><h2>💵 راتب الشهر</h2><p>الراتب الأساسي ينضاف تلقائيًا كل شهر. وإذا تغير راتب هذا الشهر، عدّل المبلغ هنا.</p><div class="field"><label>الراتب الأساسي الشهري</label><input id="base" type="number" inputmode="decimal" value="${db.salary.base||''}"></div><div class="field"><label>راتب هذا الشهر الفعلي</label><input id="actual" type="number" inputmode="decimal" value="${actual||''}"></div><button class="primary" onclick="saveSalary()">حفظ الراتب</button></div>`)}
function saveSalary(){const base=Number($('#base').value)||0,actual=Number($('#actual').value)||base;db.salary.base=base;db.salary.actual[current()]=actual;save();ensureMonth();closeModal();render()}
function incomeForm(kind='external'){openModal(`<div class="form"><h2>＋ دخل خارجي</h2><p>هذا الدخل لا يغير راتبك الشهري الأساسي.</p><div class="field"><label>المبلغ</label><input id="amount" type="number" inputmode="decimal" step="0.01"></div><div class="field"><label>من أين جاء؟</label><input id="name" placeholder="عمل إضافي، هدية، بيع، عمولة..."></div><button class="primary" onclick="addTx('income')">حفظ الدخل</button></div>`)}
function expenseForm(){openModal(`<div class="form"><h2>− مصروف جديد</h2><p>سجل أي مصروف غير موجود ضمن المصاريف الثابتة.</p><div class="field"><label>المبلغ</label><input id="amount" type="number" inputmode="decimal" step="0.01"></div><div class="field"><label>شو المصروف؟</label><input id="name" placeholder="مثلاً: غداء، بنزين، فاتورة..."></div><div class="field"><label>التصنيف</label><select id="category"><option>البيت</option><option>أكل</option><option>مواصلات</option><option>فواتير</option><option>تسوق</option><option>ترفيه</option><option>صحة</option><option>شخصي</option><option>أخرى</option></select></div><button class="primary" onclick="addTx('expense')">حفظ المصروف</button></div>`)}
function addTx(type){const amount=Number($('#amount').value),name=$('#name').value.trim();if(!(amount>0)||!name)return alert('عبّي المبلغ والوصف أولاً');db.transactions.push({id:Date.now(),type,amount,name,category:type==='expense'?$('#category').value:'دخل خارجي',date:new Date().toISOString(),icon:type==='income'?'💰':'🧾'});save();closeModal();render()}
function fixedForm(){openModal(`<div class="form"><h2>🔁 المصاريف الثابتة</h2><p>أي شيء يتكرر كل شهر. Money ينزله تلقائيًا مع بداية كل شهر.</p><div id="fixedList">${fixedList()}</div><hr style="border-color:#263246;border-width:1px 0 0;margin:18px 0"><h3 style="font-size:14px">إضافة مصروف ثابت</h3><div class="field"><label>الاسم</label><input id="fname" placeholder="الجمعية، إيجار، إنترنت..."></div><div class="field"><label>المبلغ الشهري</label><input id="famount" type="number" inputmode="decimal"></div><div class="field"><label>التصنيف</label><select id="fcat"><option>الجمعية</option><option>البيت</option><option>فواتير</option><option>مواصلات</option><option>أخرى</option></select></div><button class="primary" onclick="addFixed()">＋ إضافة للمصاريف الثابتة</button></div>`)}
function fixedList(){return db.fixed.length?db.fixed.map(f=>`<div class="list-item"><div><b>${esc(f.name)}</b><small>${fmt(f.amount)} ${db.currency} / شهر • ${esc(f.category)}</small></div><button class="small-btn" onclick="deleteFixed('${f.id}')">حذف</button></div>`).join(''):'<div class="empty">ما في مصاريف ثابتة مضافة.</div>'}
function addFixed(){const name=$('#fname').value.trim(),amount=Number($('#famount').value),category=$('#fcat').value;if(!name||!(amount>0))return alert('اكتب الاسم والمبلغ');db.fixed.push({id:Date.now().toString(),name,amount,category});save();ensureMonth();fixedForm();render()}
function deleteFixed(id){if(!confirm('حذف هذا المصروف الثابت؟'))return;db.fixed=db.fixed.filter(f=>f.id!==id);db.transactions=db.transactions.filter(t=>t.auto!=='fixed-'+id);save();fixedForm();render()}
function homeForm(){const total=monthTx().filter(t=>t.type==='expense'&&t.category==='البيت').reduce((a,t)=>a+Number(t.amount),0);openModal(`<div class="form"><h2>🏠 مصاريف البيت</h2><p>تجميع مستقل لكل ما تسجله بتصنيف البيت.</p><div class="history-box"><span>إجمالي البيت هذا الشهر</span><b style="font-size:24px">${fmt(total)} ${db.currency}</b></div><button class="primary" onclick="expenseForm();setTimeout(()=>$('#category').value='البيت',50)">＋ أضف مصروف بيت</button></div>`)}
function groupForm(){fixedForm()}
function savingForm(){openModal(`<div class="form"><h2>🎯 هدف الادخار</h2><p>تابع المبلغ الذي تريد الاحتفاظ به هذا الشهر.</p><div class="field"><label>هدف الادخار</label><input id="goal" type="number" inputmode="decimal" value="${db.savingGoal||''}"></div><button class="primary" onclick="db.savingGoal=Number($('#goal').value)||0;save();closeModal();render()">حفظ الهدف</button></div>`)}
function allTx(){const arr=[...db.transactions].sort((a,b)=>new Date(b.date)-new Date(a.date));openModal(`<div class="form"><h2>▣ كل الحركات</h2><p>${arr.length} حركة محفوظة على هذا الجهاز.</p><div class="transactions">${arr.length?arr.map(t=>`<div class="tx"><div class="tx-icon">${t.icon||'🧾'}</div><div class="tx-main"><b>${esc(t.name)}</b><small>${esc(t.category||'عام')} • ${new Date(t.date).toLocaleDateString('ar-JO')}</small></div><div class="tx-amount ${t.type==='expense'?'minus':'plus'}">${t.type==='expense'?'−':'+'}${fmt(t.amount)}</div></div>`).join(''):'<div class="empty">لا توجد حركات.</div>'}</div></div>`)}
function reports(){const hist={};db.transactions.forEach(t=>{const m=monthKey(t.date);hist[m]??={i:0,e:0};hist[m][t.type==='income'?'i':'e']+=Number(t.amount)});const rows=Object.entries(hist).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,8);openModal(`<div class="form"><h2>📊 التقارير الشهرية</h2><p>ملخص الأشهر المسجلة عندك.</p>${rows.length?rows.map(([m,v])=>`<div class="history-row" style="margin:8px 0"><div class="history-box"><span>${m}</span><b>💵 ${fmt(v.i)}</b></div><div class="history-box"><span>مصروف</span><b>🧾 ${fmt(v.e)}</b></div><div class="history-box"><span>متبقي</span><b>${fmt(v.i-v.e)}</b></div></div>`).join(''):'<div class="empty">لا توجد بيانات كافية.</div>'}</div>`)}
function settings(){openModal(`<div class="form"><h2>⚙️ الإعدادات</h2><p>كل بيانات Money محفوظة محليًا على جهازك.</p><div class="field"><label>العملة</label><select id="currency"><option ${db.currency==='JOD'?'selected':''}>JOD</option><option ${db.currency==='SAR'?'selected':''}>SAR</option><option ${db.currency==='USD'?'selected':''}>USD</option></select></div><button class="primary" onclick="db.currency=$('#currency').value;save();closeModal();render()">حفظ</button><button class="primary danger" onclick="if(confirm('مسح كل بيانات Money؟')){localStorage.removeItem(KEY);location.reload()}">مسح كل البيانات</button></div>`)}
function startAction(a){if(a==='expense')expenseForm();if(a==='salary'||a==='salarySetup')salaryForm();if(a==='external')incomeForm();if(a==='fixed'||a==='group')fixedForm();if(a==='home')homeForm();if(a==='saving')savingForm();if(a==='reports')reports()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)startAction(a.dataset.action);const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));tab.classList.add('active');if(tab.dataset.tab==='transactionsTab')allTx();if(tab.dataset.tab==='reportsTab')reports();if(tab.dataset.tab==='moreTab')settings()}});$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#settingsBtn').onclick=settings;$('#allTransactions').onclick=allTx;$('#monthReset').onclick=render;render();