const KEY='money_v3';
const old=JSON.parse(localStorage.getItem(KEY)||'null');
let db=old||{currency:'JOD',salary:{base:0,actual:{}},fixed:[],transactions:[],savingGoal:0,debts:[]};
const $=s=>document.querySelector(s),fmt=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0),save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`},current=()=>monthKey(new Date()),monthTx=()=>db.transactions.filter(t=>monthKey(t.date)===current());
const inc=()=>monthTx().filter(t=>t.type==='income').reduce((a,t)=>a+Number(t.amount),0),exp=()=>monthTx().filter(t=>t.type==='expense').reduce((a,t)=>a+Number(t.amount),0),debtPaid=()=>monthTx().filter(t=>t.type==='debtPayment').reduce((a,t)=>a+Number(t.amount),0);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function ensureMonth(){const m=current();let changed=false;const salary=db.salary.actual[m]??db.salary.base;if(salary>0&&!db.transactions.some(t=>t.auto==='salary'&&t.month===m)){db.transactions.push({id:'salary-'+m,type:'income',amount:salary,name:'راتب الشهر',category:'راتب',date:new Date(m+'-01T09:00:00').toISOString(),icon:'💵',auto:'salary',month:m});changed=true}
db.fixed.forEach(f=>{if(Number(f.amount)>0&&!db.transactions.some(t=>t.auto==='fixed-'+f.id&&t.month===m)){db.transactions.push({id:'fixed-'+f.id+'-'+m,type:'expense',amount:Number(f.amount),name:f.name,category:f.category||'ثابت',date:new Date(m+'-02T09:00:00').toISOString(),icon:f.category==='الجمعية'?'👥':'🔁',auto:'fixed-'+f.id,month:m});changed=true}});
db.debts.forEach(d=>{if(d.monthly>0&&d.active!==false&&!db.transactions.some(t=>t.auto==='debt-'+d.id&&t.month===m)){const amount=Math.min(Number(d.monthly),Number(d.remaining));if(amount>0){db.transactions.push({id:'debt-'+d.id+'-'+m,type:'debtPayment',amount,name:'سداد '+d.name,category:'سداد ديون',date:new Date(m+'-03T09:00:00').toISOString(),icon:'💳',auto:'debt-'+d.id,month:m,debtId:d.id});d.remaining=Math.max(0,Number(d.remaining)-amount);if(d.remaining===0)d.active=false;changed=true}}});if(changed)save()}
function render(){ensureMonth();const i=inc(),e=exp(),dp=debtPaid(),bal=i-e-dp;$('#available').textContent=fmt(bal);$('#spentHero').textContent=fmt(e);$('#incomeHero').textContent=fmt(i);$('#debtHero').textContent=fmt(dp);$('#incomeStat').textContent=fmt(i);$('#expenseStat').textContent=fmt(e);$('#debtStat').textContent=fmt(dp);$('#savingStat').textContent=fmt(bal);$('#currencyLabel').textContent=db.currency;$('#monthLabel').textContent=new Date().toLocaleDateString('ar-JO',{month:'long',year:'numeric'});$('#budgetProgress').style.width=i?Math.min(100,(e+dp)/i*100)+'%':'0%';$('#salaryMini').textContent=db.salary.base?`${fmt(db.salary.base)} ${db.currency} شهريًا`:'اضغط لضبط الراتب';$('#savingGoalText').textContent=db.savingGoal?`${fmt(Math.max(0,bal))} / ${fmt(db.savingGoal)} ${db.currency}`:'حدد هدفك';const home=monthTx().filter(t=>t.type==='expense'&&t.category==='البيت').reduce((a,t)=>a+Number(t.amount),0);$('#homeMini').textContent=`${fmt(home)} ${db.currency} هذا الشهر`;const gr=db.fixed.filter(f=>f.category==='الجمعية').reduce((a,f)=>a+Number(f.amount),0);$('#groupMini').textContent=gr?`${fmt(gr)} ${db.currency} شهريًا`:'أضف الجمعية';renderRecent();renderReport()}
function renderRecent(){const box=$('#recentList'),arr=[...monthTx()].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,7);box.innerHTML=arr.length?arr.map(txHtml).join(''):'<div class="empty">لسا ما سجلت حركات هذا الشهر.<br>ابدأ براتبك أو أول مصروف 💰</div>'}
function txHtml(t){const cls=t.type==='expense'?'minus':t.type==='debtPayment'?'debt-pay':'plus';return `<div class="tx"><div class="tx-icon">${t.icon||'🧾'}</div><div class="tx-main"><b>${esc(t.name)}</b><small>${esc(t.category||'عام')} • ${new Date(t.date).toLocaleDateString('ar-JO')}</small></div><div class="tx-amount ${cls}">${t.type==='expense'?'−':t.type==='debtPayment'?'↘':'+'}${fmt(t.amount)}</div></div>`}
function renderReport(){const i=inc(),e=exp(),p=i?Math.min(100,e/i*100):0;$('#reportIncome').textContent=fmt(i);$('#reportExpense').textContent=fmt(e);$('#reportBalance').textContent=fmt(i-e-debtPaid());$('#donutPct').textContent=Math.round(p)+'%';$('#donut').style.background=`conic-gradient(#6bc89b 0 ${p*3.6}deg,#263245 ${p*3.6}deg 360deg)`;const map={};monthTx().filter(t=>t.type==='expense').forEach(t=>map[t.category||'أخرى']=(map[t.category||'أخرى']||0)+Number(t.amount));const arr=Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,7),max=arr[0]?.[1]||1;$('#categoryBars').innerHTML=arr.length?arr.map(([k,v])=>`<div class="bar-row"><span>${esc(k)}</span><div class="bar-track"><div class="bar-fill" style="width:${v/max*100}%"></div></div><b>${fmt(v)}</b></div>`).join(''):'<div class="empty">سجل مصاريف لتظهر لك الرسومات.</div>'}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('show')}function closeModal(){$('#modal').classList.remove('show')}
function salaryForm(){const m=current(),actual=db.salary.actual[m]??db.salary.base;openModal(`<div class="form"><h2>💵 الراتب الشهري</h2><p>الراتب الأساسي يضاف تلقائيًا كل شهر. ويمكنك تعديل راتب هذا الشهر إذا كان فيه إضافي.</p><div class="field"><label>الراتب الأساسي الشهري</label><input id="base" type="number" inputmode="decimal" value="${db.salary.base||''}"></div><div class="field"><label>راتب هذا الشهر الفعلي</label><input id="actual" type="number" inputmode="decimal" value="${actual||''}"></div><button class="primary" onclick="saveSalary()">حفظ الراتب</button></div>`)}
function saveSalary(){db.salary.base=Number($('#base').value)||0;db.salary.actual[current()]=Number($('#actual').value)||db.salary.base;save();ensureMonth();closeModal();render()}
function incomeForm(){openModal(`<div class="form"><h2>＋ دخل خارجي</h2><p>لا يغير راتبك الأساسي.</p><div class="field"><label>المبلغ</label><input id="amount" type="number" inputmode="decimal" step="0.01"></div><div class="field"><label>من أين جاء؟</label><input id="name" placeholder="عمل إضافي، عمولة، بيع..."></div><button class="primary" onclick="addTx('income')">حفظ الدخل</button></div>`)}
function expenseForm(){openModal(`<div class="form"><h2>− مصروف جديد</h2><p>سجل أي مصروف عادي، وهو منفصل عن الديون.</p><div class="field"><label>المبلغ</label><input id="amount" type="number" inputmode="decimal" step="0.01"></div><div class="field"><label>شو المصروف؟</label><input id="name" placeholder="غداء، بنزين، فاتورة..."></div><div class="field"><label>التصنيف</label><select id="category"><option>البيت</option><option>أكل</option><option>مواصلات</option><option>فواتير</option><option>تسوق</option><option>ترفيه</option><option>صحة</option><option>شخصي</option><option>أخرى</option></select></div><button class="primary" onclick="addTx('expense')">حفظ المصروف</button></div>`)}
function addTx(type){const amount=Number($('#amount').value),name=$('#name').value.trim();if(!(amount>0)||!name)return alert('عبّي المبلغ والوصف أولاً');db.transactions.push({id:Date.now(),type,amount,name,category:type==='expense'?$('#category').value:'دخل خارجي',date:new Date().toISOString(),icon:type==='income'?'💰':'🧾'});save();closeModal();render()}
function fixedForm(){openModal(`<div class="form"><h2>🔁 المصاريف الثابتة</h2><p>تنزل تلقائيًا كل شهر، والجمعية تبقى ضمن المصروفات.</p><div id="fixedList">${db.fixed.length?db.fixed.map(f=>`<div class="list-item"><div><b>${esc(f.name)}</b><small>${fmt(f.amount)} ${db.currency} / شهر • ${esc(f.category)}</small></div><button class="small-btn" onclick="deleteFixed('${f.id}')">حذف</button></div>`).join(''):'<div class="empty">ما في مصاريف ثابتة مضافة.</div>'}</div><hr style="border-color:#263246;border-width:1px 0 0;margin:18px 0"><h3>إضافة مصروف ثابت</h3><div class="field"><label>الاسم</label><input id="fname" placeholder="الجمعية، إيجار، إنترنت..."></div><div class="field"><label>المبلغ الشهري</label><input id="famount" type="number" inputmode="decimal"></div><div class="field"><label>التصنيف</label><select id="fcat"><option>الجمعية</option><option>البيت</option><option>فواتير</option><option>مواصلات</option><option>أخرى</option></select></div><button class="primary" onclick="addFixed()">＋ إضافة</button></div>`)}
function addFixed(){const name=$('#fname').value.trim(),amount=Number($('#famount').value),category=$('#fcat').value;if(!name||!(amount>0))return alert('اكتب الاسم والمبلغ');db.fixed.push({id:Date.now().toString(),name,amount,category});save();ensureMonth();fixedForm();render()}function deleteFixed(id){if(!confirm('حذف هذا المصروف الثابت؟'))return;db.fixed=db.fixed.filter(f=>f.id!==id);db.transactions=db.transactions.filter(t=>t.auto!=='fixed-'+id);save();fixedForm();render()}
function homeForm(){const total=monthTx().filter(t=>t.type==='expense'&&t.category==='البيت').reduce((a,t)=>a+Number(t.amount),0);openModal(`<div class="form"><h2>🏠 مصاريف البيت</h2><p>تجميع مستقل لما تسجله بتصنيف البيت.</p><div class="history-box"><span>إجمالي البيت هذا الشهر</span><b>${fmt(total)} ${db.currency}</b></div><button class="primary" onclick="expenseForm();setTimeout(()=>$('#category').value='البيت',30)">＋ أضف مصروف بيت</button></div>`)}
function savingForm(){openModal(`<div class="form"><h2>🎯 هدف الادخار</h2><p>تابع المبلغ الذي تريد الاحتفاظ به.</p><div class="field"><label>هدف الادخار</label><input id="goal" type="number" inputmode="decimal" value="${db.savingGoal||''}"></div><button class="primary" onclick="db.savingGoal=Number($('#goal').value)||0;save();closeModal();render()">حفظ الهدف</button></div>`)}
function allTx(){const arr=[...db.transactions].sort((a,b)=>new Date(b.date)-new Date(a.date));openModal(`<div class="form"><h2>▣ كل الحركات</h2><p>${arr.length} حركة محفوظة على هذا الجهاز. سداد الديون ظاهر منفصلًا.</p><div class="transactions">${arr.length?arr.map(txHtml).join(''):'<div class="empty">لا توجد حركات.</div>'}</div></div>`)}
function reports(){const hist={};db.transactions.forEach(t=>{const m=monthKey(t.date);hist[m]??={i:0,e:0,d:0};hist[m][t.type==='income'?'i':t.type==='expense'?'e':'d']+=Number(t.amount)});const rows=Object.entries(hist).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,12);openModal(`<div class="form"><h2>📊 التقارير الشهرية</h2><p>المصروف والديون منفصلان.</p>${rows.length?rows.map(([m,v])=>`<div class="history-row"><div class="history-box"><span>${m}</span><b>💵 ${fmt(v.i)}</b></div><div class="history-box"><span>🧾 مصروف</span><b>${fmt(v.e)}</b></div><div class="history-box"><span>💳 ديون</span><b>${fmt(v.d)}</b></div></div>`).join(''):'<div class="empty">لا توجد بيانات.</div>'}</div>`)}
function debtTab(){ensureMonth();const total=db.debts.reduce((a,d)=>a+Number(d.remaining),0),paid=db.debts.reduce((a,d)=>a+Number(d.total)-Number(d.remaining),0),monthly=db.debts.filter(d=>d.active!==false).reduce((a,d)=>a+Math.min(Number(d.monthly)||0,Number(d.remaining)||0),0);document.querySelector('#mainContent').innerHTML=`<section class="section" style="padding-top:8px"><div class="section-head"><h2>💳 الديون</h2><button onclick="debtForm()">＋ إضافة دين</button></div><div class="hero" style="margin:0 0 12px"><div class="hero-top"><div><p class="muted">إجمالي المتبقي من الديون</p><div class="balance">${fmt(total)}</div><span class="currency">${db.currency}</span></div><div class="month">هذا الشهر<br><b>${fmt(debtPaid())}</b> مسدد</div></div><div class="hero-foot" style="margin-top:18px"><span>مسدد <b>${fmt(paid)}</b></span><span>دفعة شهرية <b>${fmt(monthly)}</b></span></div></div><div class="warning">💡 سداد الدين محسوب على المتاح من راتبك، لكن <b>لا يدخل ضمن تقارير المصروفات</b>. يمكنك تحديد دفعة شهرية تلقائية لكل دين.</div><div style="margin-top:14px">${db.debts.length?db.debts.map(debtHtml).join(''):'<div class="empty">ما عندك ديون مضافة.<br>أضف أول دين وابدأ تتبعه بسهولة.</div>'}</div></section>`}
function debtHtml(d){const total=Number(d.total)||0,rem=Math.max(0,Number(d.remaining)||0),paid=Math.max(0,total-rem),pct=total?Math.min(100,paid/total*100):100;return `<div class="debt-card"><div class="debt-head"><div><b>💳 ${esc(d.name)}</b><small>${d.active===false?'تم التسديد 🎉':'نشط'}</small></div><b>${fmt(rem)} ${db.currency}</b></div><div class="debt-number">${Math.round(pct)}% مسدد</div><div class="debt-progress"><div style="width:${pct}%"></div></div><div class="debt-meta"><span>الأصل ${fmt(total)}</span><span>الدفعة ${fmt(d.monthly||0)} / شهر</span></div><div class="debt-actions"><button onclick="payDebt('${d.id}')">💸 سدد دفعة</button><button onclick="editDebt('${d.id}')">✏️ تعديل</button></div></div>`}
function debtForm(id){const d=id?db.debts.find(x=>x.id===id):null;openModal(`<div class="form"><h2>💳 ${d?'تعديل الدين':'إضافة دين'}</h2><p>${d?'عدّل بيانات الدين.':'سجّل الدين مرة واحدة، وبعدها تابع السداد.'}</p><div class="field"><label>اسم الدين</label><input id="dname" value="${esc(d?.name||'')}" placeholder="مثلاً: قرض، لصديق..."></div><div class="field"><label>إجمالي الدين</label><input id="dtotal" type="number" inputmode="decimal" value="${d?.total||''}"></div><div class="field"><label>المتبقي حاليًا</label><input id="dremain" type="number" inputmode="decimal" value="${d?d.remaining:''}" placeholder="نفس الإجمالي إذا ما دفعت شيء"></div><div class="field"><label>دفعة شهرية من الراتب (اختياري)</label><input id="dmonthly" type="number" inputmode="decimal" value="${d?.monthly||''}" placeholder="مثلاً 100"></div><button class="primary" onclick="saveDebt('${id||''}')">حفظ الدين</button>${d?`<button class="primary danger" onclick="removeDebt('${d.id}')">حذف الدين</button>`:''}</div>`)}
function saveDebt(id){const name=$('#dname').value.trim(),total=Number($('#dtotal').value),remaining=Number($('#dremain').value||total),monthly=Number($('#dmonthly').value)||0;if(!name||!(total>0)||remaining<0||remaining>total)return alert('تأكد من اسم الدين والمبالغ');if(id){const d=db.debts.find(x=>x.id===id);d.name=name;d.total=total;d.remaining=remaining;d.monthly=monthly;d.active=remaining>0}else db.debts.push({id:Date.now().toString(),name,total,remaining,monthly,active:remaining>0});save();closeModal();debtTab()}
function payDebt(id){const d=db.debts.find(x=>x.id===id);if(!d||d.remaining<=0)return;openModal(`<div class="form"><h2>💸 سداد من «${esc(d.name)}»</h2><p>هذه الدفعة ستظهر في تبويب الديون، ولن تُحسب كمصروف عادي.</p><div class="field"><label>المبلغ</label><input id="pay" type="number" inputmode="decimal" value="${Math.min(Number(d.monthly)||Number(d.remaining),Number(d.remaining))}"></div><button class="primary" onclick="confirmPay('${d.id}')">تأكيد السداد</button></div>`)}
function confirmPay(id){const d=db.debts.find(x=>x.id===id),amount=Number($('#pay').value);if(!d||!(amount>0)||amount>d.remaining)return alert('المبلغ غير صحيح');d.remaining=Math.max(0,d.remaining-amount);if(d.remaining===0)d.active=false;db.transactions.push({id:Date.now(),type:'debtPayment',amount,name:'سداد '+d.name,category:'سداد ديون',date:new Date().toISOString(),icon:'💳',debtId:d.id});save();closeModal();debtTab()}
function editDebt(id){debtForm(id)}function removeDebt(id){if(!confirm('حذف الدين؟ سيتم حذف بياناته وحركات سداده أيضًا.'))return;db.debts=db.debts.filter(d=>d.id!==id);db.transactions=db.transactions.filter(t=>t.debtId!==id);save();debtTab()}
function settings(){openModal(`<div class="form"><h2>⚙️ الإعدادات</h2><p>بياناتك محفوظة على هذا الجهاز. بما أنك في مرحلة التجربة، يوجد زر لتصفير كل شيء.</p><div class="field"><label>العملة</label><select id="currency"><option ${db.currency==='JOD'?'selected':''}>JOD</option><option ${db.currency==='SAR'?'selected':''}>SAR</option><option ${db.currency==='USD'?'selected':''}>USD</option></select></div><button class="primary" onclick="db.currency=$('#currency').value;save();closeModal();render()">حفظ</button><button class="primary danger" onclick="resetAll()">🗑️ تصفير الموقع بالكامل</button></div>`)}
function resetAll(){if(!confirm('تأكيد التصفير؟ سيتم حذف الراتب والمصاريف والدخل والديون والتقارير من هذا الجهاز نهائيًا.'))return;if(!confirm('متأكد؟ هذا مناسب لبداية تجربة جديدة.'))return;localStorage.removeItem(KEY);db={currency:'JOD',salary:{base:0,actual:{}},fixed:[],transactions:[],savingGoal:0,debts:[]};closeModal();render();alert('تم تصفير الموقع. جاهز تبدأ من جديد ✅')}
function showHome(){location.hash='';location.reload()}function activate(tab){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='debtsTab'){debtTab()}else if(tab==='homeTab'){location.hash='';location.reload()}else if(tab==='transactionsTab'){allTx()}else if(tab==='reportsTab'){reports()}else{settings()}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){const a=b.dataset.action;({expense:expenseForm,salary:salaryForm,salarySetup:salaryForm,external:incomeForm,fixed:fixedForm,home:homeForm,group:fixedForm,saving:savingForm,reports} [a]||(()=>{}))()}const tab=e.target.closest('[data-tab]');if(tab)activate(tab.dataset.tab)});
$('#settingsBtn').onclick=settings;$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#allTransactions').onclick=allTx;render();
