const KEY='money_v1';
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{currency:'JOD',transactions:[],group:{monthly:0,total:0,paid:0},savingGoal:0};
const $=s=>document.querySelector(s); const fmt=n=>new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const monthKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}`};
const current=()=>monthKey(new Date());
const monthTx=()=>db.transactions.filter(t=>monthKey(t.date)===current());
const income=()=>monthTx().filter(t=>t.type==='income').reduce((a,t)=>a+Number(t.amount),0);
const expenses=()=>monthTx().filter(t=>t.type==='expense').reduce((a,t)=>a+Number(t.amount),0);
function render(){const inc=income(),exp=expenses(),bal=inc-exp;$('#available').textContent=fmt(bal);$('#spentHero').textContent=fmt(exp);$('#incomeHero').textContent=fmt(inc);$('#incomeStat').textContent=fmt(inc);$('#expenseStat').textContent=fmt(exp);$('#savingStat').textContent=fmt(Math.max(0,bal));$('#currencyLabel').textContent=db.currency;$('#monthLabel').textContent=new Date().toLocaleDateString('ar-JO',{month:'long',year:'numeric'});$('#budgetProgress').style.width=inc?Math.min(100,exp/inc*100)+'%':'0%';$('#savingGoalText').textContent=db.savingGoal?`${fmt(Math.max(0,bal))} / ${fmt(db.savingGoal)} ${db.currency}`:'حدد هدفك';$('#groupMini').textContent=db.group.total?`${fmt(db.group.paid)} / ${fmt(db.group.total)} ${db.currency}`:'لم تُضبط بعد';renderRecent()}
function renderRecent(){const box=$('#recentList'),arr=[...monthTx()].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6);if(!arr.length){box.innerHTML='<div class="empty">لسا ما سجلت حركات هذا الشهر.<br>ابدأ بإضافة راتبك أو أول مصروف 💰</div>';return}box.innerHTML=arr.map(t=>`<div class="tx"><div class="tx-icon">${t.icon||'🧾'}</div><div class="tx-main"><b>${esc(t.name)}</b><small>${esc(t.category||'عام')} • ${new Date(t.date).toLocaleDateString('ar-JO')}</small></div><div class="tx-amount ${t.type==='expense'?'minus':'plus'}">${t.type==='expense'?'−':'+'}${fmt(t.amount)}</div></div>`).join('')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.add('show')};function closeModal(){$('#modal').classList.remove('show')}
function expenseForm(pref=''){openModal(`<div class="form"><h2>إضافة مصروف</h2><p>سجله مرة واحدة، والباقي Money يتكفل فيه.</p><div class="field"><label>المبلغ</label><input id="amount" type="number" inputmode="decimal" step="0.01" placeholder="0.00"></div><div class="field"><label>شو المصروف؟</label><input id="name" placeholder="مثلاً: فاتورة كهرباء"></div><div class="field"><label>التصنيف</label><select id="category"><option>البيت</option><option>أكل</option><option>مواصلات</option><option>فواتير</option><option>تسوق</option><option>ترفيه</option><option>صحة</option><option>شخصي</option><option>أخرى</option></select></div><button class="primary" onclick="addTx('expense')">حفظ المصروف</button></div>`)}
function incomeForm(){openModal(`<div class="form"><h2>إضافة دخل</h2><p>سجل راتبك أو أي دخل إضافي.</p><div class="field"><label>المبلغ</label><input id="amount" type="number" inputmode="decimal" step="0.01" placeholder="0.00"></div><div class="field"><label>المصدر</label><input id="name" placeholder="راتب / عمل إضافي / غيره"></div><div class="field"><label>التصنيف</label><select id="category"><option>راتب</option><option>دخل إضافي</option><option>استرداد</option><option>أخرى</option></select></div><button class="primary" onclick="addTx('income')">حفظ الدخل</button></div>`)}
function addTx(type){const amount=Number($('#amount').value),name=$('#name').value.trim();if(!amount||amount<0||!name)return alert('عبّي المبلغ والوصف أولاً');db.transactions.push({id:Date.now(),type,amount,name,category:$('#category').value,date:new Date().toISOString(),icon:type==='income'?'💵':'🧾'});save();closeModal();render()}
function groupForm(){openModal(`<div class="form"><h2>👥 الجمعية</h2><p>خلي دفعات الجمعية والتزامها واضحين قدامك.</p><div class="field"><label>قيمة الدفعة الشهرية</label><input id="monthly" type="number" inputmode="decimal" value="${db.group.monthly||''}"></div><div class="field"><label>إجمالي الجمعية</label><input id="total" type="number" inputmode="decimal" value="${db.group.total||''}"></div><div class="field"><label>المدفوع حتى الآن</label><input id="paid" type="number" inputmode="decimal" value="${db.group.paid||''}"></div><button class="primary" onclick="saveGroup()">حفظ الجمعية</button></div>`)}
function saveGroup(){db.group={monthly:Number($('#monthly').value)||0,total:Number($('#total').value)||0,paid:Number($('#paid').value)||0};save();closeModal();render()}
function savingForm(){openModal(`<div class="form"><h2>🎯 هدف الادخار</h2><p>حدد رقمًا تريد الوصول له هذا الشهر.</p><div class="field"><label>هدف الادخار</label><input id="goal" type="number" inputmode="decimal" value="${db.savingGoal||''}" placeholder="مثلاً 500"></div><button class="primary" onclick="saveGoal()">حفظ الهدف</button></div>`)}function saveGoal(){db.savingGoal=Number($('#goal').value)||0;save();closeModal();render()}
function homeForm(){openModal(`<div class="form"><h2>🏠 مصاريف البيت</h2><p>كل مصروف تسجله تحت تصنيف «البيت» يظهر في حسابك العام.</p><button class="primary" onclick="expenseForm();setTimeout(()=>$('#category').value='البيت',0)">＋ إضافة مصروف بيت</button><button class="primary danger" onclick="showHomeTotal()">📊 إجمالي البيت هذا الشهر</button></div>`)}
function showHomeTotal(){const total=monthTx().filter(t=>t.type==='expense'&&t.category==='البيت').reduce((a,t)=>a+Number(t.amount),0);openModal(`<div class="form"><h2>🏠 البيت هذا الشهر</h2><p>إجمالي مصاريف البيت المسجلة.</p><div class="balance">${fmt(total)}</div><span class="currency">${db.currency}</span><button class="primary" onclick="closeModal()">تمام</button></div>`)}
function allTx(){const arr=[...db.transactions].sort((a,b)=>new Date(b.date)-new Date(a.date));openModal(`<div class="form"><h2>كل الحركات</h2><p>${arr.length} حركة مسجلة على هذا الجهاز.</p><div class="transactions">${arr.length?arr.map(t=>`<div class="tx"><div class="tx-icon">${t.icon||'🧾'}</div><div class="tx-main"><b>${esc(t.name)}</b><small>${esc(t.category||'عام')} • ${new Date(t.date).toLocaleDateString('ar-JO')}</small></div><div class="tx-amount ${t.type==='expense'?'minus':'plus'}">${t.type==='expense'?'−':'+'}${fmt(t.amount)}</div></div>`).join(''):'<div class="empty">لا توجد حركات.</div>'}</div></div>`)}
function settings(){openModal(`<div class="form"><h2>⚙️ الإعدادات</h2><p>بياناتك محفوظة على هذا الجهاز فقط.</p><div class="field"><label>العملة</label><select id="currency"><option ${db.currency==='JOD'?'selected':''}>JOD</option><option ${db.currency==='SAR'?'selected':''}>SAR</option><option ${db.currency==='USD'?'selected':''}>USD</option></select></div><button class="primary" onclick="db.currency=$('#currency').value;save();closeModal();render()">حفظ</button><button class="primary danger" onclick="if(confirm('مسح كل بيانات Money؟')){localStorage.removeItem(KEY);location.reload()}">مسح كل البيانات</button></div>`)}
function startAction(a){if(a==='expense')expenseForm();if(a==='income')incomeForm();if(a==='group')groupForm();if(a==='home')homeForm();if(a==='saving')savingForm()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)startAction(a.dataset.action);const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));tab.classList.add('active');if(tab.dataset.tab==='transactionsTab')allTx();if(tab.dataset.tab==='budgetTab')savingForm();if(tab.dataset.tab==='moreTab')settings()}});$('#closeModal').onclick=closeModal;$('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});$('#settingsBtn').onclick=settings;$('#allTransactions').onclick=allTx;$('#monthReset').onclick=()=>render();render();
